GET http://localhost:5192/games

###
GET  http://localhost:5192/games/19e37344-f88c-4b80-bffd-d3210f485024

###
POST http://localhost:5192/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": "80d4c16e-1b18-4041-9a76-3433a8b902f0",
  "price": 19.99,
  "releaseDate": "2011-11-18",
  "description": "A sandbox game about placing blocks and going on adventures."
}

###
PUT http://localhost:5192/games/5119b149-134a-4e7a-af14-24e12c2dbcd0
Content-Type: application/json

  {
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
  }

###
DELETE http://localhost:5192/games/730918fd-6e01-480e-a76f-1f08b208b95e

###
GET http://localhost:5192/genres