GET http://localhost:5192/games

###
GET  http://localhost:5192/games/D285C658-E312-42FF-A930-8E395B49B334

###
POST http://localhost:5192/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": "7CA608E7-63D1-41E3-91C6-AAB99A28DE91",
  "price": 19.99,
  "releaseDate": "2011-11-18",
  "description": "A sandbox game about placing blocks and going on adventures."
}

###
PUT http://localhost:5192/games/D285C658-E312-42FF-A930-8E395B49B334
Content-Type: application/json

  {
    "name": "Street Fighter II Turbo",
    "genreId": "8D3A8CEE-BAFC-49C0-B83F-E2C314FF05AF",
    "price": 9.97,
    "releaseDate": "1992-07-15",
    "description": "An enhanced version of the classic fighting game Street Fighter II."
  }

###
DELETE http://localhost:5192/games/d2e9a554-3b6f-4a64-93be-8ed9173c02f4

###
GET http://localhost:5192/genres