GET http://localhost:5192/games

###
GET  http://localhost:5192/games/75bebea2-a145-4a92-b235-ccce23c50a97

###
POST http://localhost:5192/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": "80d4c16e-1b18-4041-9a76-3433a8b902f0",
  "price": 19.99,
  "releaseDate": "2011-11-18",
  "description": "A sandbox game about placing blocks and going on adventures."
}

###
PUT http://localhost:5192/games/75bebea2-a145-4a92-b235-ccce23c50a97
Content-Type: application/json

  {
    "name": "Street Fighter II Turbo",
    "genreId": "e256264a-1377-42cb-9c1f-29f42f0c8094",
    "price": 9.99,
    "releaseDate": "1992-07-15",
    "description": "An enhanced version of the classic fighting game Street Fighter II."
  }

###
DELETE http://localhost:5192/games/730918fd-6e01-480e-a76f-1f08b208b95e

###
GET http://localhost:5192/genres